/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ProjectPraktikum.Bab1.Bab2.Bab3.Bab4.Bab5.Bab6.Bab7.Bab8.Bab9.Bab10;

import ProjectPraktikum.Bab1.Bab2.Bab3.Bab4.Bab5.Bab6.Bab7.Bab8.*;

/**
 *
 * @author icornermalang
 */
public class Gui_MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form Gui_MenuUtama
     */
    public Gui_MenuUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        Gui_mahasiswa = new javax.swing.JMenuItem();
        gui_matakuliah = new javax.swing.JMenuItem();
        gui_penilaian = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Menu Program");

        jMenu1.setText("Home");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Form");

        Gui_mahasiswa.setText("Gui_Mahasiswa");
        Gui_mahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Gui_mahasiswaActionPerformed(evt);
            }
        });
        jMenu2.add(Gui_mahasiswa);

        gui_matakuliah.setText("Gui_Matakuliah");
        gui_matakuliah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gui_matakuliahActionPerformed(evt);
            }
        });
        jMenu2.add(gui_matakuliah);

        gui_penilaian.setText("Gui_Penilaian");
        gui_penilaian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gui_penilaianActionPerformed(evt);
            }
        });
        jMenu2.add(gui_penilaian);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jLabel1)
                .addContainerGap(174, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jLabel1)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gui_penilaianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gui_penilaianActionPerformed
        // TODO add your handling code here:
        Gui_Penilaian nilai = new Gui_Penilaian();
        nilai.show();
    }//GEN-LAST:event_gui_penilaianActionPerformed

    private void Gui_mahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Gui_mahasiswaActionPerformed
        // TODO add your handling code here:
        GUI_Mahasiswa mhs = new GUI_Mahasiswa(); 
        mhs.show();
    }//GEN-LAST:event_Gui_mahasiswaActionPerformed

    private void gui_matakuliahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gui_matakuliahActionPerformed
        // TODO add your handling code here:
        GUI_DataMatkul matkul = new GUI_DataMatkul();
        matkul.show();
    }//GEN-LAST:event_gui_matakuliahActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui_MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui_MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui_MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui_MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui_MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Gui_mahasiswa;
    private javax.swing.JMenuItem gui_matakuliah;
    private javax.swing.JMenuItem gui_penilaian;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
